.TH QXGEDIT "1" "Juin 17, 2014"
.SH NOM
qxgedit \- éditeur XG en Qt
.SH SYNOPSIS
.B qxgedit
[\fIoptions\fR] [\fIfichier-syx\fR]
.SH DESCRIPTION
Cette page de manuel documente rapidement la commande
.B qxgedit
.
.PP
\fBQXGEdit\fP est une interface graphique en Qt pour l'édition des fichiers
MIDI System Exclusive pour les périphériques XG (comme le Yamaha DB50XG).
.SH OPTIONS
.HP
\fB\-h\fR, \fB\-\-help\fR
.IP
Affiche de l'aide à propos des options de ligne de commande
.HP
\fB\-v\fR, \fB\-\-version\fR
.IP
Affiche des informations de version
.SH FICHIERS
Les paramètres de configuration sont stockés dans ~/.config/rncbc.org/QXGEdit.conf
.SH AUTEUR
QXGEdit a été écrit par Rui Nuno Capela.
.PP
La version française de cette page de manuel a été traduite par Olivier Humbert
<trebmuh@tuxfamily.org>, pour le projet LibraZiK (mais peut être utilisée par
d'autres).
