
#define PACKAGE_NAME    "Qsynth"
#define PACKAGE_VERSION "0.3.4.16"

#define CONFIG_PREFIX   "."
#define CONFIG_DEBUG    1

#define CONFIG_SYSTEM_TRAY

#undef  CONFIG_FLUID_SERVER

#define CONFIG_FLUID_RESET
#define CONFIG_FLUID_BANK_OFFSET

#undef  CONFIG_FLUID_CHANNEL_INFO
#undef  CONFIG_FLUID_UNSET_PROGRAM

#define CONFIG_ROUND
#define CONFIG_GRADIENT
